export {default as Home} from './Home/Home'
export {default as Products} from './Products/Products'
export {default as Shopping} from './Shopping/Shopping'
export {default as About} from './About/About'
export {default as Contact} from './Contact/Contact'
